#!/usr/bin/env bash
#
#The file /etc/passwd has already been covered in a previous project and you should be familiar with it.
#Today we will make up a story based on it.

#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

#Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. 
#USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO

##Requirements:
#You must use the while loop (for and until are forbidden)

while IFS=':' read -r username password uid gid info home shell; do
	printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$username" "$gid" "$home" "$shell" "$uid" "$password" "$info"
done < "/etc/passwd"	
