#!/usr/bin/env bash
# While loop to display "Best School" 10 times
# On the 9th iteration, output "Hi"

counter=0

while [ $counter -lt 10 ]; do
	echo "Best School"
	if [ $counter == 8 ]
	then
		echo "Hi"
	fi
	counter=$(( counter + 1))
done
