#!/usr/bin/env bash
#
#Write a Bash script that displays numbers from 1 to 20 and:
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
#While and Case must be used

num=1

while [ $num -lt 21 ]; do
	echo "$num"
	if [ $num == 4 ]; then
		echo "bad luck from China"
	elif [ $num == 9 ]; then
		echo "bad luck from Japan"
	elif [ $num == 17 ]; then
		echo "bad luck from Italy"
	fi
	num=$(( num + 1 ))
done
