#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:

#display hours from 0 to 12
#display minutes from 1 to 59

##Requirements:

#You must use the while loop (for and until are forbidden)

hour=0
minute=1

while [ $hour -lt 13 ]; do
	echo "Hour: $hour"
	while [ $minute -lt 60 ]; do
		echo $minute
		minute=$(( minute + 1 ))
	done
	minute=1
	hour=$(( hour + 1 ))
done
